database:
  driver: mysql
  connection: root:1234@tcp(127.0.0.1:3306)/order?charset=utf8&parseTime=True&loc=UTC
eventMessageBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: pangpang-brand-order
services:
  StockApiUrl: https://staging.p2shop.com.cn/pangpang-brand/stock-api
  # calculatorApiUrl: https://staging.p2shop.com.cn/pangpang-brand/calculator-api
  # productApiUrl: https://staging.p2shop.com.cn/pangpang-brand/product-api
  # benefitApiUrl: https://staging.p2shop.com.cn/pangpang-brand/benefit-api
  benefitApiUrl: http://127.0.0.1:3001/benefit-api-pangpang-brand
  productApiUrl: http://127.0.0.1:3001/product-api-pangpang-brand
  calculatorApiUrl: http://127.0.0.1:3001/calculator-api-pangpang-brand
  placeManagementApiUrl: http://127.0.0.1:3001/place-management-api-pangpang-brand
appenv: dev
serviceName: order-api